[project]
name = "defi-contracts"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.magic-beans]
path = "contracts/magic-beans.clar"
depends_on = []
